version: "3.9"

services:
  redis:
    image: bitnami/redis:6.2.6-debian-10-r0
    container_name: dc-redis
    restart: always
    environment:
       - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
